[style]
FrameRounding = 6.0
WindowRounding = 6.0
GrabRounding = 6.0
ScrollbarRounding = 6.0
WindowPadding = [10.0, 10.0]
FramePadding = [6.0, 4.0]
ItemSpacing = [6.0, 4.0]

[colors]
Text = [0.298, 0.310, 0.412, 1.0]
TextDisabled = [0.361, 0.373, 0.466, 1.0]
TextSelectedBg = [0.914, 0.463, 0.796, 0.35]

WindowBg = [0.937, 0.945, 0.961, 1.0]
ChildBg = [0.925, 0.937, 0.949, 1.0]
PopupBg = [0.925, 0.937, 0.949, 1.0]
Border = [0.863, 0.878, 0.910, 1.0]
BorderShadow = [0,0,0,0]

FrameBg = [0.925, 0.937, 0.949, 1.0]
FrameBgHovered = [0.914, 0.463, 0.796, 1.0]
FrameBgActive = [0.914, 0.463, 0.796, 1.0]
SliderGrab = [0.914, 0.463, 0.796, 1.0]
SliderGrabActive = [0.973, 0.463, 0.796, 1.0]
CheckMark = [0.914, 0.463, 0.796, 1.0]

Button = [0.925, 0.937, 0.949, 1.0]
ButtonHovered = [0.914, 0.463, 0.796, 1.0]
ButtonActive = [0.973, 0.463, 0.796, 1.0]

Header = [0.937, 0.945, 0.961, 1.0]
HeaderHovered = [0.914, 0.463, 0.796, 1.0]
HeaderActive = [0.973, 0.463, 0.796, 1.0]
TitleBg = [0.937, 0.945, 0.961, 1.0]
TitleBgActive = [0.973, 0.463, 0.796, 1.0]
TitleBgCollapsed = [0.925, 0.937, 0.949, 1.0]
Tab = [0.937, 0.945, 0.961, 1.0]
TabHovered = [0.914, 0.463, 0.796, 1.0]
TabActive = [0.973, 0.463, 0.796, 1.0]
TabUnfocused = [0.925, 0.937, 0.949, 1.0]
TabUnfocusedActive = [0.937, 0.945, 0.961, 1.0]

MenuBarBg = [0.937, 0.945, 0.961, 1.0]
ScrollbarBg = [0.925, 0.937, 0.949, 1.0]
ScrollbarGrab = [0.914, 0.463, 0.796, 1.0]
ScrollbarGrabHovered = [0.973, 0.463, 0.796, 1.0]
ScrollbarGrabActive = [0.973, 0.463, 0.796, 1.0]

Separator = [0.863, 0.878, 0.910, 1.0]
SeparatorHovered = [0.914, 0.463, 0.796, 1.0]
SeparatorActive = [0.973, 0.463, 0.796, 1.0]
ResizeGrip = [0.925, 0.937, 0.949, 1.0]
ResizeGripHovered = [0.914, 0.463, 0.796, 1.0]
ResizeGripActive = [0.973, 0.463, 0.796, 1.0]

PlotLines = [0.863, 0.878, 0.910, 1.0]
PlotLinesHovered = [0.914, 0.463, 0.796, 1.0]
PlotHistogram = [0.863, 0.878, 0.910, 1.0]
PlotHistogramHovered = [0.914, 0.463, 0.796, 1.0]

DragDropTarget = [0.914, 0.463, 0.796, 0.9]
NavHighlight = [0.914, 0.463, 0.796, 1.0]
NavWindowingHighlight = [0.914, 0.463, 0.796, 0.7]
NavWindowingDimBg = [0.8, 0.8, 0.8, 0.2]
ModalWindowDimBg = [0.8, 0.8, 0.8, 0.35]
