[style]
FrameRounding = 6.0
WindowRounding = 6.0
GrabRounding = 6.0
ScrollbarRounding = 6.0
WindowPadding = [10.0, 10.0]
FramePadding = [6.0, 4.0]
ItemSpacing = [6.0, 4.0]

[colors]
Text = [0.25, 0.23, 0.22, 1.0]
TextDisabled = [0.42, 0.40, 0.38, 1.0]
WindowBg = [0.98, 0.97, 0.96, 1.0]
ChildBg = [0.96, 0.95, 0.94, 1.0]
PopupBg = [0.96, 0.95, 0.94, 1.0]

Border = [0.0, 0.0, 0.0, 0.0]
FrameBg = [0.94, 0.93, 0.92, 1.0]
FrameBgHovered = [0.91, 0.90, 0.89, 1.0]
FrameBgActive = [0.91, 0.90, 0.89, 1.0]

Button = [0.94, 0.93, 0.92, 1.0]
ButtonHovered = [0.91, 0.90, 0.89, 1.0]
ButtonActive = [0.91, 0.90, 0.89, 1.0]

Header = [0.94, 0.93, 0.92, 1.0]
HeaderHovered = [0.91, 0.90, 0.89, 1.0]
HeaderActive = [0.91, 0.90, 0.89, 1.0]

Separator = [0.91, 0.90, 0.89, 1.0]
SeparatorHovered = [0.91, 0.90, 0.89, 1.0]
SeparatorActive = [0.91, 0.90, 0.89, 1.0]

ResizeGrip = [0.94, 0.93, 0.92, 1.0]
ResizeGripHovered = [0.91, 0.90, 0.89, 1.0]
ResizeGripActive = [0.91, 0.90, 0.89, 1.0]

Tab = [0.94, 0.93, 0.92, 1.0]
TabHovered = [0.91, 0.90, 0.89, 1.0]
TabActive = [0.91, 0.90, 0.89, 1.0]
TabUnfocused = [0.96, 0.95, 0.94, 1.0]
TabUnfocusedActive = [0.94, 0.93, 0.92, 1.0]

PlotLines = [0.25, 0.8, 0.5, 1.0]
PlotLinesHovered = [0.3, 0.9, 0.6, 1.0]
PlotHistogram = [0.25, 0.7, 0.4, 1.0]
PlotHistogramHovered = [0.3, 0.8, 0.5, 1.0]

TextSelectedBg = [0.26, 0.59, 0.98, 0.35]
DragDropTarget = [1.0, 1.0, 0.0, 0.9]
NavHighlight = [0.26, 0.59, 0.98, 1.0]
NavWindowingHighlight = [1.0, 1.0, 0.0, 0.7]
NavWindowingDimBg = [0.8, 0.8, 0.8, 0.2]
ModalWindowDimBg = [0.8, 0.8, 0.8, 0.35]
